In [26]:
import pandas as pd
from pathlib import Path

In [50]:
# Define the path to the landing folder where the CSV files are stored
RAW_DATA_PATH = Path(
    r"C:\Users\dell\Desktop\caresync_project\caresync_project\data\landing")

# Load the CSV files into pandas DataFrames
patients = pd.read_csv(RAW_DATA_PATH / "patients.csv", low_memory=False)
encounters = pd.read_csv(RAW_DATA_PATH / "encounters.csv", low_memory=False)
organizations = pd.read_csv(
    RAW_DATA_PATH / "organizations.csv", low_memory=False)
payers = pd.read_csv(RAW_DATA_PATH / "payers.csv", low_memory=False)
providers = pd.read_csv(RAW_DATA_PATH / "providers.csv", low_memory=False)
conditions = pd.read_csv(RAW_DATA_PATH / "conditions.csv", low_memory=False)

In [ ]:
payers.head()
payers.columns = payers.columns.str.lower()
payers.rename(columns={'id': 'provider_id'}, inplace=True)
payers.columns

Index(['provider_id', 'organization', 'name', 'gender', 'speciality',
       'address', 'city', 'state', 'zip', 'lat', 'lon', 'utilization'],
      dtype='str')

In [46]:
providers.head()

,provider_id,organization,name,gender,speciality,address,city,state,zip,lat,lon,utilization
0,c23e8780-6030-37ec-8d02-8c6e3def10ac,ef58ea08-d883-3957-8300-150554edc8fb,Reginald96 Bruen238,M,GENERAL PRACTICE,60 HOSPITAL ROAD,LEOMINSTER,MA,01453,42.520838,-71.770876,1214
1,3aade15e-5333-3c4e-86c5-aab3511bc8e8,69176529-fd1f-3b3f-abce-a0a3626769eb,Lesley194 Fisher429,M,GENERAL PRACTICE,330 MOUNT AUBURN STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,2877
2,af6e425b-c7d0-313d-af54-ec0dcab69e3f,5e765f2b-e908-3888-9fc7-df2cb87beb58,Ludivina884 Steuber698,F,GENERAL PRACTICE,211 PARK STREET,ATTLEBORO,MA,02703,41.931653,-71.294503,2365
3,b64820cc-13b4-3185-946b-a208b6f3b43a,f1fbcbfb-fcfa-3bd2-b7f4-df20f1b3c3a4,Esperanza675 Escobedo608,F,GENERAL PRACTICE,ONE GENERAL STREET,LAWRENCE,MA,01842,42.700273,-71.161357,976
4,581cc2bd-9005-3008-8abb-299f40d36ca5,e002090d-4e92-300e-b41e-7d1f21dee4c6,Wilfredo622 Medhurst46,M,GENERAL PRACTICE,1493 CAMBRIDGE STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,2706

In [51]:
organizations.head()

,Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON,PHONE,REVENUE,UTILIZATION
0,ef58ea08-d883-3957-8300-150554edc8fb,HEALTHALLIANCE HOSPITALS INC,60 HOSPITAL ROAD,LEOMINSTER,MA,01453,42.520838,-71.770876,9784662000,0.0,1214
1,69176529-fd1f-3b3f-abce-a0a3626769eb,MOUNT AUBURN HOSPITAL,330 MOUNT AUBURN STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,6174923500,0.0,2877
2,5e765f2b-e908-3888-9fc7-df2cb87beb58,STURDY MEMORIAL HOSPITAL,211 PARK STREET,ATTLEBORO,MA,02703,41.931653,-71.294503,5082225200,0.0,2365
3,f1fbcbfb-fcfa-3bd2-b7f4-df20f1b3c3a4,LAWRENCE GENERAL HOSPITAL,ONE GENERAL STREET,LAWRENCE,MA,01842,42.700273,-71.161357,9786834000,0.0,976
4,e002090d-4e92-300e-b41e-7d1f21dee4c6,CAMBRIDGE HEALTH ALLIANCE,1493 CAMBRIDGE STREET,CAMBRIDGE,MA,02138,42.375967,-71.118275,6176652300,0.0,2706